### ISSUE TITLE
Misspelling when clicking green button to go full screen in OSX Client

### ISSUE THREAD

**Issue by RouteTable** [TechxArtisanStudio/Openterface_MacOS#1]
Currently says Atl + tap, Exit to full screen.  

For OSX, this should probably say Command + Tab Exit full screen mode.

<img width="560" alt="Screenshot 2024-05-07 at 1 49 11 AM" src="https://github.com/TechxArtisanStudio/Openterface_MacOS/assets/5028613/c27ee3d6-2cad-42d7-bfec-203fd378c2cf">

Build 1.2(7)

**Comment by ling3ye** [comment]
This issue is related to the following issues:
   - #4
