### ISSUE TITLE
Pressing keys at the same time on the keyboard does not respond

### ISSUE THREAD

**Issue by zerozshare** [TechxArtisanStudio/Openterface_MacOS#17]
When operating minecraft, I can't walk and jump at the same time, is there some setting that I can set to allow me to operate the keys at the same time?
macbook <=> KVM <=> mac mini

**Comment by ling3ye** [comment]
Thank you for your feedback

This issue has been fixed in the new version, please update in the App Store, the current version is v1.3. If you have other problems, please continue to feedback here, our team will do our best to quickly fix.
