### ISSUE TITLE
If you open the openterface app without connecting the Openterface device, there is a graphic defect on the right side of the screen

### ISSUE THREAD

**Issue by RouteTable** [TechxArtisanStudio/Openterface_MacOS#2]
A grey block is covering the text and graphics underneath.

<img width="697" alt="Screenshot 2024-05-07 at 2 09 07 AM" src="https://github.com/TechxArtisanStudio/Openterface_MacOS/assets/5028613/96204eed-a274-462a-9026-b0c8d41ad7ee">

Build 1.2(7)

**Comment by SebastianOsinski** [comment]
After decompiling app's asset catalog, it can be confirmed that the artefact is in the background png file `content_dark_eng.png` itself.

**Comment by kevinzjpeng** [comment]
This is a manual mistake when submit the first App Store MacOS app, it's fixed in TestFlight version MacOS app, and will be fixed in App Store release.
