### ISSUE TITLE
The app always shows Accessibility Permission Needed window on start

### ISSUE THREAD

**Issue by SebastianOsinski** [TechxArtisanStudio/Openterface_MacOS#5]
Even though the app has Accessibility permission granted, it always shows the alert when launched
 
<img width="372" alt="Screenshot 2024-05-07 at 20 52 15" src="https://github.com/TechxArtisanStudio/Openterface_MacOS/assets/2934986/21c39825-d087-4f12-8096-a032cac2c0b7">

**Comment by RouteTable** [comment]
I had this happen as well.... Here's the workaround for now:

System Preferences, Privacy & Security, Accessibility.

Find and select openterface. (You probably already had this enabled from installing the original version from the App Store.)

Click the - (minus) at the bottom of the page to delete this.  Enter your password to make the change (if applicable).

Now click the + (plus) button.  Find Openterface from the Applications list, and click open.


I don't yet know if this is simply an issue with the App Store public version vs. the Test Flight version, or if this is a bigger issue.  Definitely something that needs to have improved user experience.

**Comment by SebastianOsinski** [comment]
@RouteTable That's the exact scenario I had - I first installed the app from the AppStore and then transitioned to TF one. The solution you provided helped!

**Comment by youyoubilly** [comment]
It's better to delete the app from the App Store and use only the version from TestFlight for internal testing, as the two may conflict if they exist simultaneously.
