### ISSUE TITLE
Caps Lock does not affect typing on the target

### ISSUE THREAD

**Issue by SebastianOsinski** [TechxArtisanStudio/Openterface_MacOS#9]
When Caps Lock is activated on host's keyboard, target still receives small characters when typing.
This would probably require observing Caps Lock state and passing it to the target: https://stackoverflow.com/a/22286874/1816253

**Comment by ling3ye** [comment]
Thanks for the feedback, the issue is probably known what went wrong and has been worked on.

**Comment by ling3ye** [comment]
fixed Caps Lock issue
